package env

import (
	"reflect"
	"sort"
	"testing"
)

const lockFixture = `# @generated - this file is auto-generated by ` + "`mise lock`" + `
lockfile_version = 1

[[tools.delta]]
version = "0.19.2"
backend = "aqua:dandavison/delta"

[tools.delta."platforms.linux-x64"]
url = "https://example.com/delta-linux-x64.tar.gz"

[tools.delta."platforms.macos-arm64"]
url = "https://example.com/delta-macos-arm64.tar.gz"

[[tools.go]]
version = "1.26.8"
backend = "core:go"

[tools.go."platforms.linux-x64"]
url = "https://dl.google.com/go/go1.26.8.linux-amd64.tar.gz"

[tools.go."platforms.linux-arm64"]
url = "https://dl.google.com/go/go1.26.8.linux-arm64.tar.gz"

[tools.go."platforms.macos-arm64"]
url = "https://dl.google.com/go/go1.26.8.darwin-arm64.tar.gz"

[[tools.swift]]
version = "6.3.1"

[tools.swift."platforms.linux-x64"]
url = "https://example.com/swift-ubuntu.tar.gz"

[[tools.swift]]
version = "6.3.1"
options = { swift_platform = "fedora39" }

[tools.swift."platforms.linux-arm64"]
url = "https://example.com/swift-fedora.tar.gz"
`

func TestParseLockPlatformSets(t *testing.T) {
	got, err := ParseLock([]byte(lockFixture))
	if err != nil {
		t.Fatalf("ParseLock() error = %v", err)
	}
	for name, ps := range got {
		sort.Strings(ps)
		got[name] = ps
	}
	want := map[string][]string{
		"delta": {"linux-x64", "macos-arm64"},
		"go":    {"linux-arm64", "linux-x64", "macos-arm64"},
		// two [[tools.swift]] entries union to one platform set
		"swift": {"linux-arm64", "linux-x64"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ParseLock() = %#v, want %#v", got, want)
	}
}

func TestParseLockEmptyAndInvalid(t *testing.T) {
	if got, err := ParseLock([]byte("")); err != nil || len(got) != 0 {
		t.Fatalf("empty lock: %#v, %v", got, err)
	}
	if _, err := ParseLock([]byte("not toml [[")); err == nil {
		t.Fatal("invalid TOML must error")
	}
}
